### ISSUE TITLE
Health workers need a way to "flag" complicated cases where they need help

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/intelehealth-openmrs-ui#31] opened 2018-10-14 12:50 UTC
Corresponds to issue #549 on Android repo.

Add the flag/star as a column to active visits. These should show up at the top of active visits.

**Comment by kundanmail55** [comment] 2018-10-31 08:46
duplicate of issue #33

**Closed by kundanmail55** 2018-10-31 08:46 UTC
